name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-apache2:$(date +%s)
    - uses: actions/checkout@v4
    - name: Run the Docker image
      run: docker run -dit --name task1-apache -p 8080:80 $(ls -tr my-apache2:* | tail -n 1)
